version: "3.4"

services:
    postgres:
        image: "postgres:latest"
    
    redis:
        image: "redis:latest"

    nginx:
        depends_on:
            - client
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - "80:80"

    api:
        depends_on:
            - postgres
            - redis
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        restart: on-failure
    
    client:
        depends_on:
            - api
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - /app/node_modules
            - ./client:/app
        restart: on-failure
        
    worker:
        depends_on:
            - redis
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        restart: on-failure